In [ ]:
NumPy is a Python package for scientific computing, particularly for numerical operations on large arrays and matrices.

In [ ]:
# pip install numpy # For installation
# Syntax : pip install <package_name>  ==>used to install a package from the Python Package Index (PyPI) or other package repositories.
# pip: package manager for Python that allows users to install and manage software packages written in Python.

In [5]:
import numpy as np

In [5]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [11]:
# Create a 1D array
a=np.array([12,23,4,56,5])
print(a)
print(type(a))
print(len(a))

[12 23  4 56  5]
<class 'numpy.ndarray'>
5


In [17]:
print(a + 1)

[13 24  5 57  6]


In [19]:
a * 2

array([ 24,  46,   8, 112,  10])

In [21]:
a / 2

array([ 6. , 11.5,  2. , 28. ,  2.5])

In [ ]:
# numpy allowed any operation but list not allowed

In [23]:
l = [1,2,3]

In [27]:
print(l)
l +1


[1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [29]:
l* 2

[1, 2, 3, 1, 2, 3]

In [ ]:
#element-wise operations with lists require a bunch of code

In [37]:
for x in a:
    print(a+2)

[14 25  6 58  7]
[14 25  6 58  7]
[14 25  6 58  7]
[14 25  6 58  7]
[14 25  6 58  7]


In [39]:
a=np.array([12,23,4,56,5])
a-5

array([ 7, 18, -1, 51,  0])

In [41]:
a

array([12, 23,  4, 56,  5])

In [43]:
a*0.1

array([1.2, 2.3, 0.4, 5.6, 0.5])

In [ ]:
# we cannot apply mathematical operators directly on lists
# we can apply mathematical operators directly on Array

# List store elements of different data type
# Array store elements of same data type (homogeneous)

# NumPy operations are faster than standard Python lists.

In [45]:
x = [1,2,3,'a']
x

[1, 2, 3, 'a']

In [53]:
y=np.array([1,2,3,'a'])
print(y)

['1' '2' '3' 'a']


In [59]:
np.array(y,dtype = str)

array(['1', '2', '3', 'a'], dtype='<U11')

In [61]:
a = [2,3,4,5,6,7,8,9]

In [63]:
a[3]

5

In [65]:
a[::-1]

[9, 8, 7, 6, 5, 4, 3, 2]

In [67]:
a[4:6]

[6, 7]

In [ ]:
# dttype

In [9]:
a=np.array([2,3,4,5,6,'12'])
print(a)

['2' '3' '4' '5' '6' '12']


In [15]:
np.array(a,dtype=int)

array([ 2,  3,  4,  5,  6, 12])

In [17]:
np.array(a,dtype = float)

array([ 2.,  3.,  4.,  5.,  6., 12.])

In [19]:
np.array(a,dtype = str)

array(['2', '3', '4', '5', '6', '12'], dtype='<U11')

In [25]:
b=np.array([10,22,34,5,6,85,2,3,5,6])
print(b)
print(len(b))
print(type(b))

[10 22 34  5  6 85  2  3  5  6]
10
<class 'numpy.ndarray'>


In [27]:
b[0]

10

In [31]:
b[0:6]

array([10, 22, 34,  5,  6, 85])

In [33]:
b[-1]

6

In [35]:
b[::]

array([10, 22, 34,  5,  6, 85,  2,  3,  5,  6])

In [37]:
b[::-1]

array([ 6,  5,  3,  2, 85,  6,  5, 34, 22, 10])

In [39]:
b[::2]        ##every second element, starting from first element (1 element chodkar)

array([10, 34,  6,  2,  5])

In [41]:
b[3::4]

array([5, 3])

In [43]:
b[1] = 200

In [45]:
print(b)   #updated values 200

[ 10 200  34   5   6  85   2   3   5   6]


In [47]:
b[-1] = 1000
print(b)

[  10  200   34    5    6   85    2    3    5 1000]


In [ ]:
b=np.array([10,22,34,5,6,85,2,3,5,6])

In [51]:
b[-2:-5:-1]

array([5, 3, 2])

In [ ]:
# same as lists, ndarrays store multiple elements (is iterable) 

In [55]:
#arrays is iterable
for i in b: 
    print(i)

10
200
34
5
6
85
2
3
5
1000


In [65]:
print(b)
len(b)

[  10  200   34    5    6   85    2    3    5 1000]


10

In [67]:
b.dtype #data type of array element (int,float,complex,bool,string,object)

dtype('int32')

In [69]:
np.array(b,dtype = str)

array(['10', '200', '34', '5', '6', '85', '2', '3', '5', '1000'],
      dtype='<U11')

In [ ]:
# astype
# Array.astype(datatype)

In [71]:
b.astype(int)

array([  10,  200,   34,    5,    6,   85,    2,    3,    5, 1000])

In [73]:
b.astype(float)

array([  10.,  200.,   34.,    5.,    6.,   85.,    2.,    3.,    5.,
       1000.])

In [75]:
b.astype(str)

array(['10', '200', '34', '5', '6', '85', '2', '3', '5', '1000'],
      dtype='<U11')

In [77]:
b.astype(complex)

array([  10.+0.j,  200.+0.j,   34.+0.j,    5.+0.j,    6.+0.j,   85.+0.j,
          2.+0.j,    3.+0.j,    5.+0.j, 1000.+0.j])

In [79]:
b.astype(bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])