In [1]:
import numpy as np

In [ ]:
# NumPy operations are faster than standard Python lists.

# np.array(L,dtype=int) # Create 1D array
# Array is mutable and iterable

# Array.dtype #data type of array element (int,float,complex,bool,string,object)
# Array.astype(datatype)  #Change datatype

# Array.shape #array shape :tuple representing the dimensions of the array
# Array.ndim  # dimension
# Array.size  # no. arry elements


In [7]:
q=np.array([2,3,4,5,9,6,7,8])
q.astype(str)


array(['2', '3', '4', '5', '9', '6', '7', '8'], dtype='<U11')

In [9]:
q

array([2, 3, 4, 5, 9, 6, 7, 8])

In [ ]:
# shape:number of elements in each dimension.==>(rows,columns)

In [11]:
q.shape

(8,)

In [13]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [15]:
a.shape

(2, 4)

In [17]:
b= np.array([[1,2,3,4],[5,6,7,8],[9,8,7,6]])

In [19]:
b.shape    #3 rows 4 colums

(3, 4)

In [21]:
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
print(b)

[[1 2 3 4]
 [5 6 7 8]
 [9 8 7 6]]


In [27]:
c = np.array([[[1,2,3,4],[4,5,6,7],[7,8,9,1],[2,3,4,5]]])


In [29]:
c.shape

(1, 4, 4)

In [31]:
print(c)

[[[1 2 3 4]
  [4 5 6 7]
  [7 8 9 1]
  [2 3 4 5]]]


In [ ]:
# Get the number of dimensions of an array

In [37]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

In [41]:
c

array([[[1, 2, 3, 4],
        [4, 5, 6, 7],
        [7, 8, 9, 1],
        [2, 3, 4, 5]]])

In [47]:
q

array([2, 3, 4, 5, 9, 6, 7, 8])

In [33]:
c.ndim

3

In [35]:
b.ndim

2

In [43]:
a.ndim

2

In [45]:
q.ndim

1

In [ ]:
# arange: Returns an array with evenly spaced elements as per the interval
# arange(start, stop, step)

In [51]:
d = np.arange(10)  # same as range
print(d)

[0 1 2 3 4 5 6 7 8 9]


In [53]:
np.arange(2,5)

array([2, 3, 4])

In [55]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [59]:
# np.arange(start,stop,stepsize)
a = np.arange(0,100,5,int)
print(a)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [63]:
b=np.arange(0,50,0.5)
print(b)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5
 14.  14.5 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5 20.  20.5
 21.  21.5 22.  22.5 23.  23.5 24.  24.5 25.  25.5 26.  26.5 27.  27.5
 28.  28.5 29.  29.5 30.  30.5 31.  31.5 32.  32.5 33.  33.5 34.  34.5
 35.  35.5 36.  36.5 37.  37.5 38.  38.5 39.  39.5 40.  40.5 41.  41.5
 42.  42.5 43.  43.5 44.  44.5 45.  45.5 46.  46.5 47.  47.5 48.  48.5
 49.  49.5]


In [65]:
type(b)

numpy.ndarray

In [ ]:
# reshape to convert the array dimension
# 2D array

In [67]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [75]:
x=np.arange(18).reshape(3,6)     #3rows 6 colums
print(x)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]


In [85]:
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [83]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# shape
# ndim
# arange
# reshape