In [1]:
import numpy as np

In [ ]:
# Creating 1D array: Excel (perticular column only)

In [5]:
a=np.array([10,20,30,40])
print(a)

[10 20 30 40]


In [23]:
a.ndim

1

In [25]:
a.shape

(4,)

In [ ]:
# Creating  2D array: Excel (Row and columns)

In [11]:
b=np.array([[2,3,4,5],[5,6,7,8]])
b

array([[2, 3, 4, 5],
       [5, 6, 7, 8]])

In [13]:
b.ndim

2

In [21]:
b.shape

(2, 4)

In [ ]:
# Creating  3D array: Image

In [15]:
c=np.array([[[1,2],[3,4],[5,6]]])
c

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [17]:
c.ndim

3

In [19]:
c.shape

(1, 3, 2)

In [43]:
d=np.array([
    [
        [1,2],
        [3,4],
        [5,6]
    ],
    [
        [2,3],
        [1,2],
        [4,3]
    ]
]
   
    )

In [45]:
d

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[2, 3],
        [1, 2],
        [4, 3]]])

In [47]:
d.shape

(2, 3, 2)

In [49]:
d.ndim


3

In [59]:
x =np.arange(22)

In [61]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [63]:
x.size

22

In [69]:
a=np.arange(24)

In [71]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [77]:
b = np.reshape(a,(4,2,3), "C" )

In [79]:
b

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [81]:
b.shape # 3D Array
        # Shape (Frame, Row, Columns)

(4, 2, 3)

In [ ]:
# np.reshape(data,shape,Fill_by)
# shape= (row,col)
# Fill_by "C" ===> Fill_by Row
#         "F" ===> Fill_by column

In [85]:
a=np.arange(1,21,2)

In [87]:
# M1 ==> Prefere if input dsts id not array
np.reshape(a,(2,5),"C")

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [89]:
np.reshape(a,(2,5),"F")

array([[ 1,  5,  9, 13, 17],
       [ 3,  7, 11, 15, 19]])