In [1]:
import numpy as np

In [ ]:
# we cannot apply mathematical operators directly on lists
# we can apply mathematical operators directly on Array

# List store elements of different data type
# Array store elements of same data type (homogeneous)

# NumPy operations are faster than standard Python lists.

# np.array(L,dtype=int) # Create 1D array
# Array is mutable and iterable


# Array.shape #array shape :tuple representing the dimensions of the array
# Array.ndim  # dimension
# Array.size  # no. arry elements
# Array.dtype #data type of array element (int,float,complex,bool,string,object)
# Array.astype(datatype)  #Change datatype

# arange
# np.arange(start,stop,stepsize,dtype)
#              0           +1            Default  # fractional step count is allowed 


#linspace() :- returns evenly spaced numbers over a specified interval.
#linspace(start,  end,  num,    endpoint=True,    retstep=False)
#                      (part)   include/exclud    Gives stepsize

In [5]:
a = np.arange(2,20)
print(a)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [7]:
a.ndim

1

In [11]:
a.size

18

In [13]:
a = np.arange(2,20)
print(a)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [24]:
np.reshape(a,(2,9),"C")

array([[ 2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [26]:
np.reshape(a,(3,6),"C") #ROW WISE

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [28]:
np.reshape(a,(3,6),"f") # COLUMN WISE

array([[ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  7, 10, 13, 16, 19]])

In [32]:
a.reshape((3,6),order = 'f')

array([[ 2,  5,  8, 11, 14, 17],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  7, 10, 13, 16, 19]])

In [34]:
a = np.arange(15).reshape((3,5),order="F") #columnwise
print(a)

[[ 0  3  6  9 12]
 [ 1  4  7 10 13]
 [ 2  5  8 11 14]]


In [43]:
x = np.arange(20)

In [45]:
x
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [47]:
x.size

20

In [51]:
np.reshape(x,(5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [53]:
np.reshape(x,(5,4),order = 'f')

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [61]:
a

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [59]:
arr_transpose  = a.T
arr_transpose

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [63]:
arr_transpose  = a.T.T.T
arr_transpose

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [65]:
transpose  = a.transpose()
print(transpose)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [69]:
b = np.arange(10)
print(b)

[0 1 2 3 4 5 6 7 8 9]


In [71]:
b.size

10

In [73]:
np.reshape(b,(2,5),order = 'f')


array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [77]:
np.reshape(b,(2,5),order = 'c')

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [81]:
b.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
b.transpose()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
### Indexing and slicing NumPy arrays:

In [5]:
m = np.arange(1,10)
m

array([1, 2, 3, 4, 5, 6, 7, 8, 9])