In [1]:
# Create matrix with initial values

In [ ]:
# # Methods
# np.array()
# np.arange()
# np.linspace()

# # With initial values
# np.eye():Creates an identity matrix
# np.zeros:Creates an array filled with zeros
# np.ones():Creates an array filled with ones
# np.full():Creates an array filled with a specified value
# np.empty() : Create with random values

In [7]:
import numpy as np


In [9]:
np.eye(4)  #Creates an identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.zeros(4)

array([0., 0., 0., 0.])

In [17]:
np.zeros((3,3)) 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
# creates an array filled with a specified value
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [25]:
np.full((3,3),10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [29]:
# np.empty() : Create with random values
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [31]:
np.empty((4,5))  #random values created

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.06811083e-306, 7.56587585e-307],
       [1.37961302e-306, 1.05699242e-307, 8.01097889e-307,
        1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.42417221e-306, 7.56593017e-307,
        1.37961709e-306, 1.37962388e-306],
       [1.78018811e-306, 9.34604358e-307, 1.06810268e-306,
        8.34443864e-308, 1.42404727e-306]])

In [35]:
a=np.arange(2,20,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
a.size

9

In [39]:
a.reshape(3,3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
import numpy as np

In [ ]:
# Convert multi-dimensional arrays into one-dimensional arrays
# M1) ravel :returns a view of the original array. Changes to the new array may affect the original array and vice versa.
# M2) flatten :returns a copy of the original array. Changes to the new array do not affect the original array.
# M3) reshape

In [9]:
a =np.arange(2,31,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [11]:
a.size

15

In [15]:
z=np.reshape(a,(3,5))
z

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [17]:
a1=z.flatten()

In [19]:
a1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [25]:
a1[6] = 60

In [27]:
a1 #copy of z not affected in original array

array([ 2,  4,  6,  8, 10, 12, 60, 16, 18, 20, 22, 24, 26, 28, 30])

In [29]:
z

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [31]:
a2=z.ravel()

In [33]:
a2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [35]:
a2[7]= 70

In [37]:
a2       #it can be change in original array also

array([ 2,  4,  6,  8, 10, 12, 14, 70, 18, 20, 22, 24, 26, 28, 30])

In [39]:
z  

array([[ 2,  4,  6,  8, 10],
       [12, 14, 70, 18, 20],
       [22, 24, 26, 28, 30]])

In [41]:
z

array([[ 2,  4,  6,  8, 10],
       [12, 14, 70, 18, 20],
       [22, 24, 26, 28, 30]])

In [ ]:
# Mathematical functions

In [43]:
import numpy as np

In [47]:
C=np.arange(2,31,2)
C

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [49]:
C.size

15

In [53]:
c1=np.reshape(C,(5,3))
c1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30]])

In [55]:
c1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30]])

In [57]:
c1.sum()      ##sum over all elements in matrix

240

c1.sum(axis = 0 )

In [60]:
c1.sum(axis = 0 )  #sum of each column    [ #column ] 

array([70, 80, 90])

In [62]:
2+8+14+20+26

70

In [70]:
4+10+16+22+28

80

In [72]:
c1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30]])

In [66]:
c1.sum(axis =1)  #sum of each row 

array([12, 30, 48, 66, 84])

In [68]:
2+4+6

12

In [74]:
c1.cumsum()  #cumulative sum of all elements

array([  2,   6,  12,  20,  30,  42,  56,  72,  90, 110, 132, 156, 182,
       210, 240])

In [76]:
c1.cumsum(axis = 1)#cumulative sum for each row

array([[ 2,  6, 12],
       [ 8, 18, 30],
       [14, 30, 48],
       [20, 42, 66],
       [26, 54, 84]])

In [78]:
c1.cumsum(axis = 0)

array([[ 2,  4,  6],
       [10, 14, 18],
       [24, 30, 36],
       [44, 52, 60],
       [70, 80, 90]])

In [80]:
c1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30]])

In [82]:
c1.max()

30

In [84]:
c1.min()

2

In [86]:
c1.max(axis = 0 )

array([26, 28, 30])

In [88]:
c1.min(axis = 1)

array([ 2,  8, 14, 20, 26])

In [90]:
c1.mean()

16.0

In [94]:
np.median(c1)

16.0

In [96]:
c1.std()

8.640987597877148

In [98]:
c1.var()


74.66666666666667

In [100]:
np.percentile(c1,10)

4.800000000000001

In [15]:
import numpy as np

In [25]:
x=np.arange(2,20)
x

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [27]:
x.size

18

In [41]:
z=np.reshape(x,(3,6))
z

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19]])

In [43]:
z.flatten()


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [45]:
z.sort()

In [49]:
np.sqrt(x)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
       4.12310563, 4.24264069, 4.35889894])

In [51]:
np.sqrt(25)

5.0

In [53]:
np.exp(5)

148.4131591025766

In [55]:
np.exp(x)

array([7.38905610e+00, 2.00855369e+01, 5.45981500e+01, 1.48413159e+02,
       4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
       2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
       1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
       6.56599691e+07, 1.78482301e+08])

In [57]:
#natural logarithm
np.log(x)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015, 2.07944154, 2.19722458, 2.30258509, 2.39789527,
       2.48490665, 2.56494936, 2.63905733, 2.7080502 , 2.77258872,
       2.83321334, 2.89037176, 2.94443898])

In [59]:
np.abs(x)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [61]:
 #element-wise rounding up
np.ceil(x)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19.])

In [63]:
np.floor(x)# #element-wise rounding down

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19.])