In [ ]:
# Manipulate arrays

In [ ]:
# np.append(): adds values to the end of an array. It returns a new array
# np.concatenate(): Combines two or more arrays along a specified axis
# np.vstack(): Stacks arrays vertically (row-wise)
# np.hstack(): Stacks arrays horizontally (column-wise)
#  "stack" refers to the operation of joining multiple arrays along a new axis

In [1]:
import numpy as np

In [51]:
a = np.arange(1,16).reshape(3,5)


In [53]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [55]:
b=np.arange(21,36).reshape(3,5)
b

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [33]:
c=np.append(a,b)

In [35]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 21, 22,
       23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [57]:
np.append(a,b ,axis=0) #row wise

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [59]:
np.append(a,b ,axis=1) #column wise

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [43]:
a.size

15

In [45]:
b.size

15

In [61]:
a.ndim

2

In [49]:
b.ndim

2

In [63]:
# combining
# M1)concatenate
np.concatenate((a,b),axis=0) #row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [65]:
np.concatenate((a,b),axis=1) #col

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [69]:
# M2
np.vstack((a,b))       #row wise   0

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [71]:
np.hstack((a,b)) 

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [73]:
# m3
np.row_stack((a,b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [75]:
np.column_stack((a,b))

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [79]:
# m4
np.r_[a,b]  #row

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [81]:
np.c_[a,b] #col

array([[ 1,  2,  3,  4,  5, 21, 22, 23, 24, 25],
       [ 6,  7,  8,  9, 10, 26, 27, 28, 29, 30],
       [11, 12, 13, 14, 15, 31, 32, 33, 34, 35]])

In [85]:
# splitting

x=np.r_[a,b]
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [87]:
np.vsplit(a,3) 

[array([[1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10]]),
 array([[11, 12, 13, 14, 15]])]

In [ ]:
hsplit()

In [ ]:
# M1 --> NP.APPENDE(A,B , AXIS = 0) -->ROWWISE
# M2 -->NP.VSTACK((A,B)) -->ROWWISE
# M3 -->NP.R_[A,B] -->ROWWISSE
# M4 -->NP.R_STACK(A,B) -->ROWWISE

# SPLIT -->HOLD NOT UDERSTAND!!VSPLIT 


In [97]:
x=np.arange(1,15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [99]:
x<4

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False])

In [101]:
x[x<4]  #values showing 

array([1, 2, 3])

In [105]:
x[~x < 4]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])